#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#                       This file was automatically generated from modular_openpangu_dense.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_openpangu_dense.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨

# coding=utf-8
# Copyright (c) 2025 Huawei Technologies Co., Ltd. All rights reserved.
# Copyright 2022 EleutherAI and the HuggingFace Inc. team. All rights reserved.
#
# This code is based on EleutherAI's GPT-NeoX library and the GPT-NeoX
# and OPT implementations in this library. It has been modified from its
# original forms to accommodate minor architectural differences compared
# to GPT-NeoX and OPT used by the Meta AI team that trained the model.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from typing import Callable, Optional, Union

import torch
from torch import nn
import triton
import triton.language as tl
import math
NPU_ATTN_INFR = False

from transformers.activations import ACT2FN
from transformers.cache_utils import Cache, DynamicCache
from transformers.generation import GenerationMixin
from transformers.masking_utils import create_causal_mask
from transformers.modeling_flash_attention_utils import FlashAttentionKwargs
from transformers.modeling_layers import GradientCheckpointingLayer
from transformers.modeling_outputs import (
    BaseModelOutputWithPast,
    CausalLMOutputWithPast,
    SequenceClassifierOutputWithPast,
)
from transformers.modeling_rope_utils import ROPE_INIT_FUNCTIONS, dynamic_rope_update
from transformers.modeling_utils import ALL_ATTENTION_FUNCTIONS, PreTrainedModel
from transformers.processing_utils import Unpack
from transformers.utils import LossKwargs, auto_docstring, can_return_tuple, logging
from .configuration_openpangu_dense import PanguEmbeddedConfig


logger = logging.get_logger(__name__)


def create_lower_triangular_matrix(batch_size, num_heads, context_size):
    # 创建一个下三角掩码矩阵，形状为 (context_size, context_size)
    lower_triangular_mask = torch.triu(torch.full((context_size , context_size ), -65504.0),diagonal=1)
    return lower_triangular_mask.to('cuda')
# triton sparse attn
@triton.jit
def selected_query_sparse_attention_fwd_kernel_gqa(
    Q_selected, # [batch_size, num_q_heads, selected_q_num, head_dim]
    K, # [batch_size, num_kv_heads, context_size, head_dim]
    V, # [batch_size, num_kv_heads, context_size, head_dim]
    batch_size, num_q_heads, num_kv_heads, context_size,
    q_idx,  # [batch_size, num_q_heads, selected_q_num]
    q_size,
    Out,
    stride_qz, stride_qh, stride_qm, stride_qk,
    stride_sqz, stride_sqh, stride_sqm, stride_sqk,
    stride_kz, stride_kh, stride_kn, stride_kk,
    stride_vz, stride_vh, stride_vn, stride_vk,
    stride_oz, stride_oh, stride_om, stride_ok,
    stride_idxz, stride_idxh, stride_idxm,
    NUM_ROWS,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
    BLOCK_DMODEL: tl.constexpr,
    dtype: tl.constexpr,
    scale: tl.constexpr,
):
    # grid 的两个维度（2，1）
    start_m = tl.program_id(0)  # 当前是第几块（在 q_size 维度）
    off_hz = tl.program_id(1)  # batch_size*num_q_heads 维上的第几块

    batch_idx = off_hz // num_q_heads
    q_head_idx = off_hz % num_q_heads
    
    # GQA: 计算对应的 kv head index
    # num_q_heads_per_kv = num_q_heads // num_kv_heads
    kv_head_idx = q_head_idx // (num_q_heads // num_kv_heads)
    
    # 当前pid 在 query 维度的偏移
    offs_m = start_m * BLOCK_M + tl.arange(0, BLOCK_M) # [0,... BLOCK_M-1]
    # 当前pid 在 context 维度的偏移
    offs_n = tl.arange(0, BLOCK_N) # [0,... BLOCK_N-1]
    # 当前pid 在 head_dim 维度的偏移
    offs_d = tl.arange(0, BLOCK_DMODEL) # [0,... head_dim-1]
    
    # query 起始偏移量 在前两个维度
    sq_offset = batch_idx * stride_sqz + q_head_idx * stride_sqh
    o_offset = batch_idx * stride_oz + q_head_idx * stride_oh

    # key/value 起始偏移量 在前两个维度（使用 kv_head_idx）
    kv_offset = batch_idx * stride_kz + kv_head_idx * stride_kh
    
    if start_m * BLOCK_M >= q_size:
        return
    
    # 加载 q_idx 并确保不越界
    cols_ptr = q_idx + batch_idx * stride_idxz + q_head_idx * stride_idxh + start_m * BLOCK_M * stride_idxm
    cols_mask = offs_m < q_size
    # 特定 query 的索引
    q_cols = tl.load(cols_ptr + offs_m % BLOCK_M, mask=cols_mask, other=0)

    # 当前 query索引中的最大值
    max_qcol = tl.max(q_cols, axis=0)

    q_ptrs = Q_selected + sq_offset + offs_m[:, None] * stride_sqm + offs_d[None, :] * stride_sqk
    k_ptrs = K + kv_offset + offs_d[:, None] * stride_kk # [[0],... [head_dim-1]]
    v_ptrs = V + kv_offset + offs_d[None, :] * stride_vk # [[0,... head_dim-1]]

    o_ptrs = Out + o_offset + offs_m[:, None] * stride_om + offs_d[None, :] * stride_ok

    # 确保 q_cols 不越界
    valid_mask = q_cols < context_size
    # 从Q_selected的q_ptrs load q
    q = tl.load(q_ptrs)

    # 每个query 最大注意力权重
    m_i = tl.zeros([BLOCK_M], dtype=tl.float32) - float("inf")
    # 每个query 累计权重
    l_i = tl.zeros([BLOCK_M], dtype=tl.float32)
    # 累计 o
    acc = tl.zeros([BLOCK_M, BLOCK_DMODEL], dtype=tl.float32)
    # qk_scale= head_dim ** -0.5 / 1.44269504
    qk_scale = 1 / scale
    q = (q * qk_scale).to(dtype)
    
    # 按块遍历上下文
    for start_n in range(0, max_qcol + 1, BLOCK_N):
        # 当前块的context 索引
        cols = start_n + offs_n # [BLOCK_N]
        n_mask = cols < context_size # [BLOCK_N]
        k_mask = cols <= max_qcol
        k = tl.load(k_ptrs + cols[None, :] * stride_kn, mask=n_mask[None, :], other=0.0)
        v = tl.load(v_ptrs + cols[:, None] * stride_vn, mask=n_mask[:, None], other=0.0)
        qk = tl.zeros([BLOCK_M, BLOCK_N], dtype=tl.float32)
        qk += tl.dot(q, k)

        # 边界检查，确保 cols 和 q_cols 都在合法范围内
        qk = tl.where(cols[None, :] <= q_cols[:, None], qk, float("-inf"))
        m_i_new = tl.maximum(m_i, tl.max(qk, 1))
        alpha = tl.math.exp(m_i - m_i_new)
        p = tl.math.exp(qk - m_i_new[:, None])

        acc_scale = l_i * 0 + alpha
        acc *= acc_scale[:, None]
        acc += tl.dot(p.to(dtype), v)

        l_i = l_i * alpha + tl.sum(p, 1)
        m_i = m_i_new
    
    acc /= l_i[:, None]
    # 在写回输出之前也要确保不越界
    tl.store(o_ptrs, acc.to(dtype), mask=offs_m[:, None] < q_size)


def selected_query_attention_entrance_gqa(
    sq: torch.Tensor,  # [batch_size, num_q_heads, selected_q_num, head_dim]
    k: torch.Tensor,  # [batch_size, num_kv_heads, context_size, head_dim]
    v: torch.Tensor,  # [batch_size, num_kv_heads, context_size, head_dim]
    q_idx: torch.Tensor,  # [batch_size, num_q_heads, selected_q_num]
    block_size_M: int = 64, 
    block_size_N: int = 64, 
):
    dq, dk, dv = sq.shape[-1], k.shape[-1], v.shape[-1]
    assert dq == dk and dk == dv
    
    q_size = q_idx.shape[-1]
    batch_size, num_q_heads, _, head_dim = sq.shape
    _, num_kv_heads, context_size, _ = k.shape
    
    # GQA 检查: num_q_heads 必须是 num_kv_heads 的倍数
    assert num_q_heads % num_kv_heads == 0, \
        f"num_q_heads ({num_q_heads}) must be divisible by num_kv_heads ({num_kv_heads})"

    o = torch.zeros(batch_size, num_q_heads, q_size, head_dim, device=sq.device, dtype=sq.dtype)
    grid = (triton.cdiv(q_size, block_size_M), batch_size * num_q_heads)
    dtype = tl.bfloat16 if sq.dtype == torch.bfloat16 else tl.float16
    
    selected_query_sparse_attention_fwd_kernel_gqa[grid](
        sq, k, v,
        batch_size, num_q_heads, num_kv_heads, context_size,
        q_idx,
        q_size,
        o,
        sq.stride(0), sq.stride(1), sq.stride(2), sq.stride(3),
        sq.stride(0), sq.stride(1), sq.stride(2), sq.stride(3),
        k.stride(0), k.stride(1), k.stride(2), k.stride(3),
        v.stride(0), v.stride(1), v.stride(2), v.stride(3),
        o.stride(0), o.stride(1), o.stride(2), o.stride(3),
        q_idx.stride(0), q_idx.stride(1), q_idx.stride(2),
        (q_size + block_size_M - 1) // block_size_M,
        BLOCK_M=block_size_M, BLOCK_N=block_size_N,
        BLOCK_DMODEL=head_dim,
        dtype=dtype,
        num_warps=4, num_stages=2,
        scale=math.sqrt(head_dim)
    )
    return o


def selected_query_sparse_attention_gqa(
    query_selected: torch.Tensor, # [batch_size, num_q_heads, selected_q_num, head_dim]
    key: torch.Tensor,    # [batch_size, num_kv_heads, context_size, head_dim]
    value: torch.Tensor,  # [batch_size, num_kv_heads, context_size, head_dim]
    q_idx: torch.Tensor,  # [batch_size, num_q_heads, selected_q_num]
    block_size_M: int = 64, 
    block_size_N: int = 64, 
):
    batch_size, num_q_heads, _, head_dim = query_selected.shape
    _, num_kv_heads, context_size, _ = key.shape
    
    # GQA 检查
    assert num_q_heads % num_kv_heads == 0, \
        f"num_q_heads ({num_q_heads}) must be divisible by num_kv_heads ({num_kv_heads})"

    q_size = q_idx.shape[-1]
    
    # Padding for block alignment
    pad_MS = (block_size_M - (q_size % block_size_M)) % block_size_M
    if pad_MS > 0:
        query_selected = torch.nn.functional.pad(query_selected, [0, 0, 0, pad_MS, 0, 0, 0, 0])

    pad_N = (block_size_N - (context_size % block_size_N)) % block_size_N
    if pad_N > 0:
        key = torch.nn.functional.pad(key, [0, 0, 0, pad_N, 0, 0, 0, 0])
        value = torch.nn.functional.pad(value, [0, 0, 0, pad_N, 0, 0, 0, 0])

    # Padding for head_dim to be power of 2
    if head_dim not in [16, 32, 64, 128, 256, 512]:
        target_dim = 2 ** math.ceil(math.log2(head_dim))
        pad_dim = target_dim - head_dim
        query_selected = torch.nn.functional.pad(query_selected, [0, pad_dim, 0, 0, 0, 0, 0, 0])
        key = torch.nn.functional.pad(key, [0, pad_dim, 0, 0, 0, 0, 0, 0])
        value = torch.nn.functional.pad(value, [0, pad_dim, 0, 0, 0, 0, 0, 0])

    q_idx = q_idx.to(torch.int32).reshape((batch_size, num_q_heads, -1))
    
    out = selected_query_attention_entrance_gqa(
        query_selected, key, value,
        q_idx, block_size_M, block_size_N
    )
    
    return out[..., :q_size, :head_dim]

class PanguEmbeddedRMSNorm(nn.Module):
    def __init__(self, hidden_size, eps=1e-6):
        """
        PanguEmbeddedRMSNorm is equivalent to T5LayerNorm
        """
        super().__init__()
        self.weight = nn.Parameter(torch.ones(hidden_size))
        self.variance_epsilon = eps

    def forward(self, hidden_states):
        input_dtype = hidden_states.dtype
        hidden_states = hidden_states.to(torch.float32)
        variance = hidden_states.pow(2).mean(-1, keepdim=True)
        hidden_states = hidden_states * torch.rsqrt(variance + self.variance_epsilon)
        return self.weight * hidden_states.to(input_dtype)

    def extra_repr(self):
        return f"{tuple(self.weight.shape)}, eps={self.variance_epsilon}"


class PanguEmbeddedRotaryEmbedding(nn.Module):
    def __init__(self, config: PanguEmbeddedConfig, device=None):
        super().__init__()
        # BC: "rope_type" was originally "type"
        if hasattr(config, "rope_scaling") and config.rope_scaling is not None:
            self.rope_type = config.rope_scaling.get("rope_type", config.rope_scaling.get("type"))
        else:
            self.rope_type = "default"
        self.max_seq_len_cached = config.max_position_embeddings
        self.original_max_seq_len = config.max_position_embeddings

        self.config = config
        self.rope_init_fn = ROPE_INIT_FUNCTIONS[self.rope_type]

        inv_freq, self.attention_scaling = self.rope_init_fn(self.config, device)
        self.register_buffer("inv_freq", inv_freq, persistent=False)
        self.original_inv_freq = self.inv_freq

    @torch.no_grad()
    @dynamic_rope_update  # power user: used with advanced RoPE types (e.g. dynamic rope)
    def forward(self, x, position_ids):
        inv_freq_expanded = self.inv_freq[None, :, None].float().expand(position_ids.shape[0], -1, 1).to(x.device)
        position_ids_expanded = position_ids[:, None, :].float()

        device_type = x.device.type if isinstance(x.device.type, str) and x.device.type != "mps" else "cpu"
        with torch.autocast(device_type=device_type, enabled=False):  # Force float32
            freqs = (inv_freq_expanded.float() @ position_ids_expanded.float()).transpose(1, 2)
            emb = torch.cat((freqs, freqs), dim=-1)
            cos = emb.cos() * self.attention_scaling
            sin = emb.sin() * self.attention_scaling

        return cos.to(dtype=x.dtype), sin.to(dtype=x.dtype)


def rotate_half(x):
    """Rotates half the hidden dims of the input."""
    x1 = x[..., : x.shape[-1] // 2]
    x2 = x[..., x.shape[-1] // 2 :]
    return torch.cat((-x2, x1), dim=-1)


def apply_rotary_pos_emb(q, k, cos, sin, position_ids=None, unsqueeze_dim=1):
    """Applies Rotary Position Embedding to the query and key tensors.

    Args:
        q (`torch.Tensor`): The query tensor.
        k (`torch.Tensor`): The key tensor.
        cos (`torch.Tensor`): The cosine part of the rotary embedding.
        sin (`torch.Tensor`): The sine part of the rotary embedding.
        position_ids (`torch.Tensor`, *optional*):
            Deprecated and unused.
        unsqueeze_dim (`int`, *optional*, defaults to 1):
            The 'unsqueeze_dim' argument specifies the dimension along which to unsqueeze cos[position_ids] and
            sin[position_ids] so that they can be properly broadcasted to the dimensions of q and k. For example, note
            that cos[position_ids] and sin[position_ids] have the shape [batch_size, seq_len, head_dim]. Then, if q and
            k have the shape [batch_size, heads, seq_len, head_dim], then setting unsqueeze_dim=1 makes
            cos[position_ids] and sin[position_ids] broadcastable to the shapes of q and k. Similarly, if q and k have
            the shape [batch_size, seq_len, heads, head_dim], then set unsqueeze_dim=2.
    Returns:
        `tuple(torch.Tensor)` comprising of the query and key tensors rotated using the Rotary Position Embedding.
    """
    cos = cos.unsqueeze(unsqueeze_dim)
    sin = sin.unsqueeze(unsqueeze_dim)
    q_embed = (q * cos) + (rotate_half(q) * sin)
    k_embed = (k * cos) + (rotate_half(k) * sin)
    return q_embed, k_embed


class PanguEmbeddedMLP(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.config = config
        self.hidden_size = config.hidden_size
        self.intermediate_size = config.intermediate_size
        self.gate_proj = nn.Linear(self.hidden_size, self.intermediate_size, bias=False)
        self.up_proj = nn.Linear(self.hidden_size, self.intermediate_size, bias=False)
        self.down_proj = nn.Linear(self.intermediate_size, self.hidden_size, bias=False)
        self.act_fn = ACT2FN[config.hidden_act]

    def forward(self, x):
        down_proj = self.down_proj(self.act_fn(self.gate_proj(x)) * self.up_proj(x))
        return down_proj


def repeat_kv(hidden_states: torch.Tensor, n_rep: int) -> torch.Tensor:
    """
    This is the equivalent of torch.repeat_interleave(x, dim=1, repeats=n_rep). The hidden states go from (batch,
    num_key_value_heads, seqlen, head_dim) to (batch, num_attention_heads, seqlen, head_dim)
    """
    batch, num_key_value_heads, slen, head_dim = hidden_states.shape
    if n_rep == 1:
        return hidden_states
    hidden_states = hidden_states[:, :, None, :, :].expand(batch, num_key_value_heads, n_rep, slen, head_dim)
    return hidden_states.reshape(batch, num_key_value_heads * n_rep, slen, head_dim)


def eager_attention_forward(
    module: nn.Module,
    query: torch.Tensor,
    key: torch.Tensor,
    value: torch.Tensor,
    attention_mask: Optional[torch.Tensor],
    scaling: float,
    dropout: float = 0.0,
    **kwargs,
):
    key_states = repeat_kv(key, module.num_key_value_groups)
    value_states = repeat_kv(value, module.num_key_value_groups)

    attn_weights = torch.matmul(query, key_states.transpose(2, 3)) * scaling
    if attention_mask is not None:
        causal_mask = attention_mask[:, :, :, : key_states.shape[-2]]
        attn_weights = attn_weights + causal_mask

    attn_weights = nn.functional.softmax(attn_weights, dim=-1, dtype=torch.float32).to(query.dtype)
    attn_weights = nn.functional.dropout(attn_weights, p=dropout, training=module.training)
    attn_output = torch.matmul(attn_weights, value_states)
    attn_output = attn_output.transpose(1, 2).contiguous()

    return attn_output, attn_weights


class PanguEmbeddedAttention(nn.Module):
    """Multi-headed attention from 'Attention Is All You Need' paper"""

    def __init__(self, config: PanguEmbeddedConfig, layer_idx: int):
        super().__init__()
        self.config = config
        self.layer_idx = layer_idx
        self.head_dim = getattr(config, "head_dim", config.hidden_size // config.num_attention_heads)
        self.num_heads = config.num_attention_heads
        self.num_key_value_heads = config.num_key_value_heads
        self.num_key_value_groups = config.num_attention_heads // config.num_key_value_heads
        self.scaling = self.head_dim**-0.5
        self.attention_dropout = config.attention_dropout
        self.is_causal = True

        self.q_proj = nn.Linear(config.hidden_size, config.num_attention_heads * self.head_dim, bias=config.bias)
        self.k_proj = nn.Linear(config.hidden_size, config.num_key_value_heads * self.head_dim, bias=config.bias)
        self.v_proj = nn.Linear(config.hidden_size, config.num_key_value_heads * self.head_dim, bias=config.bias)
        self.o_proj = nn.Linear(config.num_attention_heads * self.head_dim, config.hidden_size, bias=config.bias)

    def forward(
        self,
        hidden_states: torch.Tensor,
        position_embeddings: tuple[torch.Tensor, torch.Tensor],
        attention_mask: Optional[torch.Tensor],
        past_key_value: Optional[Cache] = None,
        cache_position: Optional[torch.LongTensor] = None,
        **kwargs: Unpack[FlashAttentionKwargs],
    ) -> tuple[torch.Tensor, Optional[torch.Tensor], Optional[tuple[torch.Tensor]]]:
        input_shape = hidden_states.shape[:-1]
        hidden_shape = (*input_shape, -1, self.head_dim)

        query_states = self.q_proj(hidden_states).view(hidden_shape).transpose(1, 2)
        key_states = self.k_proj(hidden_states).view(hidden_shape).transpose(1, 2)
        value_states = self.v_proj(hidden_states).view(hidden_shape).transpose(1, 2)

        cos, sin = position_embeddings
        query_states, key_states = apply_rotary_pos_emb(query_states, key_states, cos, sin)

        if past_key_value is not None:
            # sin and cos are specific to RoPE models; cache_position needed for the static cache
            cache_kwargs = {"sin": sin, "cos": cos, "cache_position": cache_position}
            key_states, value_states = past_key_value.update(key_states, value_states, self.layer_idx, cache_kwargs)

        attention_interface: Callable = eager_attention_forward
        if self.config._attn_implementation != "eager":
            attention_interface = ALL_ATTENTION_FUNCTIONS[self.config._attn_implementation]
        
        if query_states.shape != key_states.shape and "dense" in kwargs.keys() and kwargs['dense'] == 2:
            attn_output = selected_query_sparse_attention_gqa(query_states, \
                                                            key_states, value_states, cache_position.unsqueeze(0)[:,None,:].repeat(1, self.num_heads, 1)).to(query_states.dtype)
            attn_weights = None
            attn_output = attn_output.transpose(1, 2)
        else:
            attn_output, attn_weights = attention_interface(
                self,
                query_states,
                key_states,
                value_states,
                attention_mask,
                dropout=0.0 if not self.training else self.attention_dropout,
                scaling=self.scaling,
                **kwargs,
            )


        if 'reprocess_method' in kwargs.keys():
            if kwargs['reprocess_method'] == 'FusionRAG':
                passages_len = kwargs['passages_len']
                history_key_cache = kwargs['history_key_cache']
                if self.layer_idx == self.config.num_hidden_layers - 1:
                    # 先不管 question 中提示
                    for context_id, context_len in enumerate(passages_len[:-1]):
                        if context_id < 1:
                            continue
                        
                        past_len = sum(passages_len[:context_id])
                        context_key = history_key_cache[context_id].to(query_states.device)[self.layer_idx]
                        context_key = repeat_kv(context_key, self.num_key_value_groups)
                        context_key = context_key.transpose(-1, -2)
                        attn_weights = torch.matmul(query_states, context_key)
                        attn_weights /= math.sqrt(self.head_dim)
                        attn_weights = nn.functional.softmax(attn_weights, dim = -1, dtype = torch.float16)
                        attn_weights = torch.sum(torch.sum(attn_weights, dim=0),dim=-2)
                        assert not torch.isinf(attn_weights).any()
                        assert not torch.isnan(attn_weights).any()
                        assert context_len == attn_weights.shape[1]
                        past_key_value.importance_cache[self.layer_idx].narrow(1,past_len,context_len).copy_(attn_weights)
            elif kwargs["reprocess_method"] == "Cache-Craft" and self.layer_idx == self.config.num_hidden_layers - 1:
                passages_len = kwargs['passages_len']
                total_len = sum(passages_len)
                query_len = passages_len[-1]
                target_query = query_states[:, :, -query_len:, :]
                if total_len == query_states.shape[2]:
                    target_key = key_states[:, :, cache_position, :]
                elif total_len > query_states.shape[2] and query_len == query_states.shape[2]:
                    target_key = key_states[:, :, :cache_position[-1]+1, :]
                head_dim = query_states.shape[-1]
                scaling_factor = head_dim ** 0.5
                if target_query.shape[1] != target_key.shape[1]:
                    target_key = repeat_kv(target_key, self.num_key_value_groups)
                attention_scores = torch.einsum('bhqd,bhkd->bhqk', target_query, target_key) / scaling_factor
                mask = attention_mask[:, :, :total_len, :total_len]
                mask = mask[:, :, -query_len:, :]
                attention_scores += mask
                attention_scores = torch.nn.functional.softmax(attention_scores, dim=-1)
                attention_scores = attention_scores[:, :, :, :-query_len]
                attention_scores = attention_scores.squeeze(0).sum(dim=[2])
                past_key_value.importance_cache.append(attention_scores)
            elif kwargs['reprocess_method'] == "speculative_prefill":
                passages_len = kwargs['passages_len']
                total_len = sum(passages_len)
                query_len = passages_len[-1]
                context_key = repeat_kv(key_states, self.num_key_value_groups)
                context_key = context_key.transpose(-1, -2)
                attn_weights = torch.matmul(query_states, context_key)
                attn_weights /= math.sqrt(self.head_dim)
                attn_weights = nn.functional.softmax(attn_weights, dim = -1, dtype = torch.float16)
                attn_weights = attn_weights[:, :, -query_len:, :-query_len]
                attn_weights = torch.sum(torch.sum(attn_weights, dim=0),dim=-2)
                past_key_value.importance_cache[self.layer_idx].narrow(1,0,sum(passages_len[:-1])).copy_(attn_weights)
        attn_output = attn_output.reshape(*input_shape, -1).contiguous()
        attn_output = self.o_proj(attn_output)
        return attn_output, attn_weights


class PanguEmbeddedDecoderLayer(GradientCheckpointingLayer):
    def __init__(self, config: PanguEmbeddedConfig, layer_idx: int):
        super().__init__()
        self.hidden_size = config.hidden_size
        self.self_attn = PanguEmbeddedAttention(config=config, layer_idx=layer_idx)
        self.mlp = PanguEmbeddedMLP(config)
        self.input_layernorm = PanguEmbeddedRMSNorm(config.hidden_size, eps=config.rms_norm_eps)
        self.post_attention_layernorm = PanguEmbeddedRMSNorm(config.hidden_size, eps=config.rms_norm_eps)

    def forward(
        self,
        hidden_states: torch.Tensor,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_value: Optional[Cache] = None,
        output_attentions: Optional[bool] = False,
        use_cache: Optional[bool] = False,
        cache_position: Optional[torch.LongTensor] = None,
        position_embeddings: Optional[tuple[torch.Tensor, torch.Tensor]] = None,  # necessary, but kept here for BC
        **kwargs: Unpack[FlashAttentionKwargs],
    ) -> tuple[torch.FloatTensor, Optional[tuple[torch.FloatTensor, torch.FloatTensor]]]:
        residual = hidden_states
        hidden_states = self.input_layernorm(hidden_states)

        # Self Attention
        hidden_states, self_attn_weights = self.self_attn(
            hidden_states=hidden_states,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_value=past_key_value,
            output_attentions=output_attentions,
            use_cache=use_cache,
            cache_position=cache_position,
            position_embeddings=position_embeddings,
            **kwargs,
        )
        hidden_states = residual + hidden_states

        # Fully Connected
        residual = hidden_states
        hidden_states = self.post_attention_layernorm(hidden_states)
        hidden_states = self.mlp(hidden_states)
        hidden_states = residual + hidden_states

        outputs = (hidden_states,)
        if output_attentions:
            outputs += (self_attn_weights,)

        return outputs


@auto_docstring
class PanguEmbeddedPreTrainedModel(PreTrainedModel):
    config_class = PanguEmbeddedConfig
    base_model_prefix = "model"
    supports_gradient_checkpointing = True
    _no_split_modules = ["PanguEmbeddedDecoderLayer"]
    _skip_keys_device_placement = ["past_key_values"]
    _supports_flash_attn_3 = True
    _supports_flash_attn_2 = True
    _supports_sdpa = True
    _supports_flex_attn = True
    _supports_cache_class = True
    _supports_quantized_cache = True
    _supports_static_cache = True
    _supports_attention_backend = True

    def _init_weights(self, module):
        std = self.config.initializer_range
        if isinstance(module, nn.Linear):
            module.weight.data.normal_(mean=0.0, std=std)
            if module.bias is not None:
                module.bias.data.zero_()
        elif isinstance(module, nn.Embedding):
            module.weight.data.normal_(mean=0.0, std=std)
            if module.padding_idx is not None:
                module.weight.data[module.padding_idx].zero_()
        elif isinstance(module, PanguEmbeddedRMSNorm):
            module.weight.data.fill_(1.0)


@auto_docstring
class PanguEmbeddedModel(PanguEmbeddedPreTrainedModel):
    def __init__(self, config: PanguEmbeddedConfig):
        super().__init__(config)
        self.padding_idx = config.pad_token_id
        self.vocab_size = config.vocab_size

        self.embed_tokens = nn.Embedding(config.vocab_size, config.hidden_size, self.padding_idx)
        self.layers = nn.ModuleList(
            [PanguEmbeddedDecoderLayer(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
        )
        self.norm = PanguEmbeddedRMSNorm(config.hidden_size, eps=config.rms_norm_eps)
        self.rotary_emb = PanguEmbeddedRotaryEmbedding(config=config)
        self.gradient_checkpointing = False

        # Initialize weights and apply final processing
        self.post_init()

    def get_input_embeddings(self):
        return self.embed_tokens

    def set_input_embeddings(self, value):
        self.embed_tokens = value

    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        input_ids: Optional[torch.LongTensor] = None,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        inputs_embeds: Optional[torch.FloatTensor] = None,
        use_cache: Optional[bool] = None,
        output_attentions: Optional[bool] = None,
        output_hidden_states: Optional[bool] = None,
        cache_position: Optional[torch.LongTensor] = None,
        **flash_attn_kwargs: Unpack[FlashAttentionKwargs],
    ) -> BaseModelOutputWithPast:
        output_attentions = output_attentions if output_attentions is not None else self.config.output_attentions
        output_hidden_states = (
            output_hidden_states if output_hidden_states is not None else self.config.output_hidden_states
        )
        use_cache = use_cache if use_cache is not None else self.config.use_cache

        if (input_ids is None) ^ (inputs_embeds is not None):
            raise ValueError("You must specify exactly one of input_ids or inputs_embeds")

        if self.gradient_checkpointing and self.training and use_cache:
            logger.warning_once(
                "`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`."
            )
            use_cache = False

        # TODO (joao): remove this exception in v4.56 -- it exists for users that try to pass a legacy cache
        if not isinstance(past_key_values, (type(None), Cache)):
            raise ValueError("The `past_key_values` should be either a `Cache` object or `None`.")

        if inputs_embeds is None:
            inputs_embeds = self.embed_tokens(input_ids)

        if use_cache and past_key_values is None:
            past_key_values = DynamicCache()

        if cache_position is None:
            past_seen_tokens = past_key_values.get_seq_length() if past_key_values is not None else 0
            cache_position = torch.arange(
                past_seen_tokens, past_seen_tokens + inputs_embeds.shape[1], device=inputs_embeds.device
            )

        if position_ids is None:
            position_ids = cache_position.unsqueeze(0)

        causal_mask = create_causal_mask(
            config=self.config,
            input_embeds=inputs_embeds,
            attention_mask=attention_mask,
            cache_position=cache_position,
            past_key_values=past_key_values,
            position_ids=position_ids,
        )

        hidden_states = inputs_embeds

        # create position embeddings to be shared across the decoder layers
        position_embeddings = self.rotary_emb(hidden_states, position_ids)

        # decoder layers
        all_hidden_states = () if output_hidden_states else None
        all_self_attns = () if output_attentions else None

        for decoder_layer in self.layers[: self.config.num_hidden_layers]:
            if output_hidden_states:
                all_hidden_states += (hidden_states,)

            layer_outputs = decoder_layer(
                hidden_states,
                attention_mask=causal_mask,
                position_ids=position_ids,
                past_key_value=past_key_values,
                output_attentions=output_attentions,
                use_cache=use_cache,
                cache_position=cache_position,
                position_embeddings=position_embeddings,
                **flash_attn_kwargs,
            )

            hidden_states = layer_outputs[0]

            if output_attentions:
                all_self_attns += (layer_outputs[1],)

        hidden_states = self.norm(hidden_states)

        # add hidden states from the last decoder layer
        if output_hidden_states:
            all_hidden_states += (hidden_states,)

        return BaseModelOutputWithPast(
            last_hidden_state=hidden_states,
            past_key_values=past_key_values if use_cache else None,
            hidden_states=all_hidden_states,
            attentions=all_self_attns,
        )


class KwargsForCausalLM(FlashAttentionKwargs, LossKwargs): ...


@auto_docstring
class PanguEmbeddedForCausalLM(PanguEmbeddedPreTrainedModel, GenerationMixin):
    _tied_weights_keys = ["lm_head.weight"]
    _tp_plan = {"lm_head": "colwise_rep"}
    _pp_plan = {"lm_head": (["hidden_states"], ["logits"])}

    def __init__(self, config):
        super().__init__(config)
        self.model = PanguEmbeddedModel(config)
        self.vocab_size = config.vocab_size
        self.lm_head = nn.Linear(config.hidden_size, config.vocab_size, bias=False)

        # Initialize weights and apply final processing
        self.post_init()

    def get_input_embeddings(self):
        return self.model.embed_tokens

    def set_input_embeddings(self, value):
        self.model.embed_tokens = value

    def get_output_embeddings(self):
        return self.lm_head

    def set_output_embeddings(self, new_embeddings):
        self.lm_head = new_embeddings

    def set_decoder(self, decoder):
        self.model = decoder

    def get_decoder(self):
        return self.model

    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        input_ids: Optional[torch.LongTensor] = None,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        inputs_embeds: Optional[torch.FloatTensor] = None,
        labels: Optional[torch.LongTensor] = None,
        use_cache: Optional[bool] = None,
        output_attentions: Optional[bool] = None,
        output_hidden_states: Optional[bool] = None,
        cache_position: Optional[torch.LongTensor] = None,
        logits_to_keep: Union[int, torch.Tensor] = 0,
        **kwargs: Unpack[KwargsForCausalLM],
    ) -> CausalLMOutputWithPast:
 
        output_attentions = output_attentions if output_attentions is not None else self.config.output_attentions
        output_hidden_states = (
            output_hidden_states if output_hidden_states is not None else self.config.output_hidden_states
        )

        # decoder outputs consists of (dec_features, layer_state, dec_hidden, dec_attn)
        outputs: BaseModelOutputWithPast = self.model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            inputs_embeds=inputs_embeds,
            use_cache=use_cache,
            output_attentions=output_attentions,
            output_hidden_states=output_hidden_states,
            cache_position=cache_position,
            **kwargs,
        )

        hidden_states = outputs.last_hidden_state
        # Only compute necessary logits, and do not upcast them to float if we are not computing the loss
        slice_indices = slice(-logits_to_keep, None) if isinstance(logits_to_keep, int) else logits_to_keep
        logits = self.lm_head(hidden_states[:, slice_indices, :])

        loss = None
        if labels is not None:
            loss = self.loss_function(logits=logits, labels=labels, vocab_size=self.config.vocab_size, **kwargs)

        return CausalLMOutputWithPast(
            loss=loss,
            logits=logits,
            past_key_values=outputs.past_key_values,
            hidden_states=outputs.hidden_states,
            attentions=outputs.attentions,
        )


__all__ = [
    "PanguEmbeddedForCausalLM",
    "PanguEmbeddedModel",
    "PanguEmbeddedPreTrainedModel",
]