[build-system]
requires = [
  "setuptools",
  "torch == 2.3.1", 
  "ninja",
  "packaging"
  ]
build-backend = "setuptools.build_meta"

[project]
name = "ktransformers"
version = "0.1.0"
dependencies = [
  "torch >= 2.3.0,<=2.3.1",
  "transformers == 4.43.2",
  "fastapi >= 0.111.0",
  "langchain >= 0.2.0",
  "blessed >= 1.20.0",
  "accelerate >= 0.31.0",
  "sentencepiece >= 0.1.97",
  "setuptools",
  "ninja",
  "wheel",
  "colorlog",
  "build",
  "packaging",
  "fire"
]
requires-python = ">=3.10"
authors = [
  {name = "kvcache.ai", email = "kvcache-ai@approaching.ai"}
]
maintainers = [
  {name = "awake", email = "awake@approaching.ai"}
]
description = "A very fast framework that can run LLMs on a laptop"
readme = "README.md"
license = {file = "LICENSE"}
keywords = ["ktransformers", "llm"]
classifiers = [
  "Programming Language :: Python"
]

[project.scripts]
ktransformers = "ktransformers.server.main:main"

[tool.setuptools.packages.find]
where = ["./", ]
include = ["ktransformers"]

