chunk_size: 10240
max_seq_len: 128000
block_size: 128
local_windows_len: 4096
second_select_num: 1000
threads_num: 64
anchor_type: DYNAMIC
kv_type: FP16
dense_layer_num: 0
anchor_num: 1
preselect_block: True
head_select_mode: SHARED
preselect_block_count: 96
layer_step: 1
token_step: 1